MaisonViande-Web/src/main/java/fr/eql/ai110/maisonviande/controller/DisplayManagedBean.java
package fr.eql.ai110.maisonviande.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import fr.eql.ai110.maisonviande.entity.Category;
import fr.eql.ai110.maisonviande.entity.Product;
import fr.eql.ai110.maisonviande.entity.Unit;
import fr.eql.ai110.maisonviande.entity.User;
import fr.eql.ai110.maisonviande.ibusiness.CategoryIBusiness;
import fr.eql.ai110.maisonviande.ibusiness.ProductIBusiness;
import fr.eql.ai110.maisonviande.ibusiness.UnitIBusiness;

@ManagedBean(name="mbDisplay")
@SessionScoped
public class DisplayManagedBean implements Serializable{

	private static final long serialVersionUID = 1L;

	private List<Category> categories;
	private List<Product> products;
	private List<Unit> Units;
	private Product detailledProducts;
	private Category categorySelected;
	

	@EJB
	private CategoryIBusiness categoryBusiness;
	@EJB
	private ProductIBusiness productBusiness;
	@EJB
	private UnitIBusiness unitBusiness;

	@PostConstruct
	public void init() {
		User user = new User();
		categories = categoryBusiness.getCategories();
		Units = unitBusiness.getUnits();
		FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
        user = (User) session.getAttribute("connectedClient");

        try {
        	System.out.println("-------------- User en session : "+ user.getLogin() + "-------------------------") ;
		} catch (Exception e) {
			System.out.println("-------------- Pas d'User en Session ------------------------>"+ user);
		}
		
	}

	public String detailCategory(Category category) {
		String forward = "/categorydetail.xhtml?faces-redirection=true";
		products = productBusiness.getProductsFromCategory(category);
		categorySelected = category;
		return forward;
	}
	
	public String detailProduct(Product products) {
		String forward = "/productdetail.xhtml?faces-redirection=true";
		detailledProducts = products;
		return forward;
	}
	
	
	public List<Category> getCategories() {
		return categories;
	}

	public void setCategories(List<Category> categories) {
		this.categories = categories;
	}

	public List<Product> getProducts() {
		return products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}

	public Product getDetailledProducts() {
		return detailledProducts;
	}

	public void setDetailledProducts(Product detailledProducts) {
		this.detailledProducts = detailledProducts;
	}

	public Category getCategorySelected() {
		return categorySelected;
	}

	public void setCategorySelected(Category categorySelected) {
		this.categorySelected = categorySelected;
	}

	public List<Unit> getUnits() {
		return Units;
	}

	public void setUnits(List<Unit> units) {
		Units = units;
	}
	
	
}

MaisonViande-Web/src/main/java/fr/eql/ai110/maisonviande/controller/LoginManagedBean.java
package fr.eql.ai110.maisonviande.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import fr.eql.ai110.maisonviande.entity.Purshase;
import fr.eql.ai110.maisonviande.entity.User;
import fr.eql.ai110.maisonviande.ibusiness.UserIBusiness;

@ManagedBean(name="mbLogin")
@SessionScoped
public class LoginManagedBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private List<User> users;
	
	private String login;
	private String password;
	private String name;
	private String surname;
	
	private User user;
	
	private Boolean isConnected = false;

	@EJB
	private UserIBusiness userBusiness;
	
	@PostConstruct
	public void init() {
		User user = new User();
		users = userBusiness.getAll();
		FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
        user = (User) session.getAttribute("connectedClient");
        
        try {
        	System.out.println("-------------- User en session : "+ user.getLogin() + "-------------------------") ;
		} catch (Exception e) {
			System.out.println("-------------- Pas d'User en Session ------------------------>"+ user);
		}
	}

	public String create() {
		String forward = "/login.xhtml?faces-redirection=true";

		// instancier un Utilisateur :
		User user = new User();
		user.setLogin(login);
		user.setName(name);
		user.setSurname(surname);

		// enregistrer le nouvel utilisateur (business)
		userBusiness.create(user, password);
		System.out.println("ManagedBeanLevel :" + password);

		return forward;
	}


	public String connect() {
		String forward = null;
		System.out.println("*********************************Methode connect*******************************************");
		setUser(userBusiness.connect(login, password));
		if (user != null) {
			isConnected = true;
			FacesContext facesContext = FacesContext.getCurrentInstance();
			HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
			session.setAttribute("connectedClient", user);
			forward = "/account.xhtml?faces-redirection=true";
		} else {
			isConnected = false;
			FacesMessage facesMessage = new FacesMessage(
					FacesMessage.SEVERITY_WARN, 
					"Identifiant et/ou mot de passe incorrect(s)",
					"Identifiant et/ou mot de passe incorrect(s)"
					);
			FacesContext.getCurrentInstance().addMessage("loginForm:inpLogin", facesMessage);
			FacesContext.getCurrentInstance().addMessage("loginForm:inpPassword", facesMessage);
			forward = "/login.xhtml?faces-redirection=false";
		}
		try {
			System.out.println("------------------------- valeur user : "+ user.getLogin() + " ------------------------");
		} catch (Exception e) {
			System.out.println("------------------------- valeur user : "+ user + " ------------------------");
		}
		
		return forward;
	}

	public String disconnect() {
		HttpSession session = (HttpSession) FacesContext
				.getCurrentInstance()
				.getExternalContext()
				.getSession(true);
		session.invalidate();
		setUser(null);
		return "/logout.xhtml?faces-redirection=true";
	}
	
	public List<Purshase> getPurshaseByUser() {
		
		return userBusiness.getPurshasesByUser(user);
	}
	
	//GETTERS & SETTERS

	public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public UserIBusiness getUserBusiness() {
		return userBusiness;
	}

	public void setUserBusiness(UserIBusiness userBusiness) {
		this.userBusiness = userBusiness;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Boolean getIsConnected() {
		return isConnected;
	}

	public void setIsConnected(Boolean isConnected) {
		this.isConnected = isConnected;
	}	
	
	

}

MaisonViande-Web/src/main/java/fr/eql/ai110/maisonviande/controller/PurshaseManageBean.java
package fr.eql.ai110.maisonviande.controller;

import java.io.Serializable;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import fr.eql.ai110.maisonviande.entity.Cart;
import fr.eql.ai110.maisonviande.entity.CommandLign;
import fr.eql.ai110.maisonviande.entity.Item;
import fr.eql.ai110.maisonviande.entity.Product;
import fr.eql.ai110.maisonviande.entity.Purshase;
import fr.eql.ai110.maisonviande.entity.Statut;
import fr.eql.ai110.maisonviande.entity.User;
import fr.eql.ai110.maisonviande.ibusiness.CategoryIBusiness;
import fr.eql.ai110.maisonviande.ibusiness.PurshaseIBusiness;
import fr.eql.ai110.maisonviande.ibusiness.StatutIBusiness;
import fr.eql.ai110.maisonviande.ibusiness.UserIBusiness;
import net.bootsfaces.utils.FacesMessages;

@ManagedBean(name="mbPurshase")
@SessionScoped
public class PurshaseManageBean implements Serializable {


	private static final long serialVersionUID = 1L;

	private User user;
	private List<Purshase> purshases;
	private Double totalAmount = 0.0;

	private String totalAmountParsed ="";

	private Integer quantity;
	private Cart cart = new Cart();
	private List<Statut> statuts;

	private List<Item> items = new ArrayList<Item>();

	@EJB
	private CategoryIBusiness categoryBusiness;
	@EJB
	private PurshaseIBusiness purshaseBusiness;
	@EJB
	private StatutIBusiness statutBusiness;
	@EJB
	private UserIBusiness userBusiness;

	@PostConstruct
	public void init() {
		totalAmountParsed = "0.00";
		statuts = statutBusiness.getStatuts();

		FacesContext facesContext = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
		user = (User) session.getAttribute("connectedClient");
		purshases = purshaseBusiness.getAll();

		try {
			System.out.println("-------------- User en session : "+ user.getLogin() + "-------------------------") ;
		} catch (Exception e) {
			System.out.println("-------------- Pas d'User en Session ------------------------>"+ user);
		}
	}

	public String addToCart(Product product) {
		String forward = "/categorydetail.xhtml?faces-redirection=true";
		Item item = new Item();
		item.setProduct(product);
		item.setQuantity(quantity);


		items = cart.getItems();
		Boolean doesProductExist = false;

		for (Item itemTest : items) {
			if(itemTest.getProduct().equals(product)) {
				itemTest.setQuantity(itemTest.getQuantity()+quantity);
				doesProductExist = true;

				totalAmount = totalAmount + (item.getProduct().gethTAmount().floatValue()*item.getQuantity());
				System.out.println(totalAmount.toString());

				System.out.println("**************************************** MAJ Panier **************************************");
				
				FacesMessages.info("La quantité " , "à été mise à jours");
			}
		}
		if (doesProductExist == false) {

			totalAmount = totalAmount + (item.getProduct().gethTAmount().floatValue()*item.getQuantity());
			System.out.println(totalAmount.toString());

			cart.addToItems(item);
			System.out.println("**************************************** Nouveau(x) produit(s) ajouté(s) au panier **************************************");
			
			FacesMessages.info(item.getProduct().getName().toString(), " à été ajouté au panier");
		}

		try {
			System.out.println("-------------- User en session : "+ user.getLogin() + "-------------------------") ;
		} catch (Exception e) {
			System.out.println("-------------- Pas d'User en Session ------------------------>"+ user);
		}
		totalAmountParsed = purshaseBusiness.doubleTotalAmountParsed(totalAmount);
		
		return forward;		
	}

	public String validatePurshase() {
		String forward = null;
		FacesContext facesContext = FacesContext.getCurrentInstance();
		HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
		user = (User) session.getAttribute("connectedClient");

		try {
			System.out.println("---------------- " + user.getLogin() + " is on session ----------------------");
		} catch (Exception e) {
			System.out.println("!!!!!!!!!----------------- is no USER on session ----------!!!!!!!!!!!!!!!!!!!!");
		}
		
		System.out.println("total dans le panier : " + totalAmount.toString());
		
		{if(totalAmount <= 0.0) {
			System.out.println("******************************Panier vide !************************");
			FacesMessage facesMessage = new FacesMessage(
					FacesMessage.SEVERITY_WARN, 
					"Votre panier est vide",
					"Votre panier est vide"
					);
			FacesContext.getCurrentInstance().addMessage("inpPanierLog", facesMessage);
			forward = "/panier.xhtml?faces-redirection=false";
		}else {		
			if (user != null) {
				Purshase purshase = new Purshase();
				purshase.setPurchaseDate(LocalDate.now());
				purshase.setStatut(statuts.get(0));
				purshase.setUser(user);
				purshase.setTotalAmount(totalAmount);
				purshase.setTotalAmountParsed(totalAmountParsed);
				purshaseBusiness.addPurshase(purshase);

				Purshase lastPurshaseEntry = purshaseBusiness.getLastEntry();
				System.out.println(lastPurshaseEntry.getId());


				for (Item item : items) {
					CommandLign commandLign = new CommandLign();
					commandLign.setQuantity(item.getQuantity());
					commandLign.setProduct(item.getProduct());
					commandLign.setPurshase(lastPurshaseEntry);
					purshaseBusiness.addCommandLign(commandLign);

				} 
				forward = "/purshaseRecap.xhtml?faces-redirection=true";
			}else {
			System.out.println("******************************Connection Requise************************");
			FacesMessage facesMessage = new FacesMessage(
					FacesMessage.SEVERITY_WARN, 
					"Connection requise",
					"Connection requise"
					);
			FacesContext.getCurrentInstance().addMessage("inpPanierEmpty", facesMessage);
			forward = "/panier.xhtml?faces-redirection=false"; 
		}
		}
		}
		return forward;
	}

	public String ShoppingCartEmpty() {
		setCart(null);
		totalAmount = 0.0;
		totalAmountParsed = purshaseBusiness.doubleTotalAmountParsed(totalAmount);
		setCart(cart=new Cart());
		FacesMessages.info("Votre panier ", "est vide.");
		return "/panier.xhtml?faces-redirection=true";
	}

	public Integer getQuantity() {
		return quantity;
	}
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public Cart getCart() {
		return cart;
	}
	public void setCart(Cart cart) {
		this.cart = cart;
	}
	public List<Item> getItems() {
		return items;
	}
	public void setItems(List<Item> items) {
		this.items = items;
	}
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public List<Statut> getStatuts() {
		return statuts;
	}
	public void setStatuts(List<Statut> statuts) {
		this.statuts = statuts;
	}
	public List<Purshase> getPurshase() {
		return purshases;
	}
	public void setPurshase(List<Purshase> purshase) {
		this.purshases = purshase;
	}

	public Double getTotalAmount() {
		return totalAmount;
	}

	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	public String getTotalAmountParsed() {
		return totalAmountParsed;
	}

	public void setTotalAmountParsed(String totalAmountParsed) {
		this.totalAmountParsed = totalAmountParsed;
	}




}

MaisonViande-Web/src/main/webapp/account.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core%22%3E">

<ui:composition template="/arch.xhtml">
	<ui:define name="content">

		<h3>Vos Informations</h3>
		<h:dataTable styleClass="myTable" value="#{mbLogin.user}" var="user">
			<h:column>
				<f:facet name="header">Identifiant</f:facet>
                            #{user.login}
                        </h:column>
			<h:column>
				<f:facet name="header">Prénom</f:facet>
                            #{user.surname}
                        </h:column>
			<h:column>
				<f:facet name="header">Nom</f:facet>
                            #{user.name}
                        </h:column>
			<h:column>
				<f:facet name="header">numéro et nom de rue</f:facet>
                            #{user.numAndStreetName}
                        </h:column>
			<h:column>
				<f:facet name="header">code postale et ville</f:facet>
                            #{user.cpAndCity}
                        </h:column>
			<h:column>
				<f:facet name="header">Email</f:facet>
                            #{user.mail}
                        </h:column>
			<h:column>
				<f:facet name="header">Téléphone</f:facet>
                            #{user.phone}
                        </h:column>
		</h:dataTable>

		<h3>Vos commandes</h3>
		<ui:repeat value="#{mbLogin.purshaseByUser}" var="purshUser">
			<div class="flex-purshase-recap">
				<p:panelGrid styleClass="purshase-grid">
					<p:row styleClass="pushase-bot">
						<p:column styleClass="grid-center-col">Référence de commande</p:column>
						<p:column styleClass="grid-center-col">Statut de la commande</p:column>
						<p:column styleClass="grid-center-col">Prix total</p:column>
					</p:row>
					<p:row styleClass="pushase-content">
						<p:column styleClass="grid-center-col">#{purshUser.id}</p:column>
						<p:column styleClass="grid-center-col">#{purshUser.statut.label}</p:column>
						<p:column styleClass="grid-center-col">#{purshUser.totalAmountParsed}€</p:column>
					</p:row>
					<p:row styleClass="pushase-top-bot">
						<p:column styleClass="grid-center-col">Quantité</p:column>
						<p:column styleClass="grid-center-col">Produit</p:column>
						<p:column styleClass="grid-center-col">Prix unitaire</p:column>
					</p:row>
					<ui:repeat var="comLign" value="#{purshUser.commandLigns}">
						<p:row styleClass="pushase-content">
							<p:column styleClass="grid-center-col">#{comLign.quantity}</p:column>
							<p:column styleClass="grid-center-col">#{comLign.product.name.toUpperCase()}</p:column>
							<p:column styleClass="grid-center-col">#{comLign.product.hTAmount}€</p:column>
						</p:row>
					</ui:repeat>
				</p:panelGrid>
			</div>
			<br />

		</ui:repeat>

	</ui:define>
</ui:composition>
</html>

MaisonViande-Web/src/main/webapp/arch.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core%22%3E">


<h:head>
	<ui:insert name="head"></ui:insert>
	<link rel="icon" type="image/png"
		href="#{request.contextPath}/resources/pictures/enseigne.ico" />
	<title>Maison de la Viande</title>
	<h:outputStylesheet library="css" name="style.css" position="last" />
</h:head>
<h:body>
	<b:navBar brand="LA MAISON DE LA VIANDE"
		brand-img="#{request.contextPath}/resources/pictures/enseigne.png"
		brandHref="index.xhtml" fixed="top" fluid="true"
		class="navbar-light bg-light" brand-img-style-class="logoNavbar"
		style-class="navbarStyle">
		<b:navbarLinks pull="left">
			<b:navbarLinks>
				<b:navLink value="Contact" icon-awesome="envelope"
					href="contact.xhtml"></b:navLink>
				<b:navLink value="Bonjour #{mbLogin.user.surname}"
					icon-awesome="user" href="account.xhtml"
					rendered="#{mbLogin.isConnected}"></b:navLink>
				<b:navLink value="Connexion" icon-awesome="key" href="login.xhtml"
					rendered="#{!mbLogin.isConnected}"></b:navLink>
				<b:navLink value="Deconnexion" icon-awesome="close"
					href="logout.xhtml" rendered="#{mbLogin.isConnected}"></b:navLink>
				<b:navLink value="Panier" icon-awesome="shopping-cart"
					href="panier.xhtml"></b:navLink>
				<b:growl id="growl" allow-dismiss="true" globalOnly="true"
					showDetail="true" severity="info,warn,error"
					placementFrom="top" animation-enter="animated slideInDown"
					animation-exit="animated fadeOutDown" />
			</b:navbarLinks>
		</b:navbarLinks>
		<b:navbarLinks pull="right">
			<b:navbarLinks>
				<b:form>
					<ui:repeat var="category" value="#{mbDisplay.categories}">
						<b:commandButton value="#{category.label}"
							action="#{mbDisplay.detailCategory(category)}"
							style-class="btn-default-CAT" />
					</ui:repeat>
				</b:form>
			</b:navbarLinks>
		</b:navbarLinks>
	</b:navBar>



	<b:row>
		<b:column style-class="content">
			<ui:insert name="content"></ui:insert>
		</b:column>
	</b:row>

	<div class="footer">
		<h3>LaMaisonDeLaViande - 2022</h3>
	</div>
</h:body>

</html>

MaisonViande-Web/src/main/webapp/categorydetail.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core%22%3E">

<ui:composition template="/arch.xhtml">
	<ui:define name="content">
		<div class="marginLR">
			<h1>#{mbDisplay.categorySelected.label}</h1>
			<h3>#{mbDisplay.categorySelected.description}</h3>
			<div class="flex-categorydetails">
				<h:form>
					<ui:repeat value="#{mbDisplay.products}" var="product">
						<div class="flex-catdetailitem">

							<h:graphicImage value="/resources/pictures/#{product.image}"
								styleClass="category-max-width" />
							<br />
							<b:commandButton style-class="button-category-detail"
								value="#{product.name.toUpperCase()}"
								action="#{mbDisplay.detailProduct(product)}" />
						</div>
					</ui:repeat>
				</h:form>
			</div>
		</div>
	</ui:define>
</ui:composition>
</html>

MaisonViande-Web/src/main/webapp/contact.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core%22%3E">

<ui:composition template="/arch.xhtml">
	<ui:define name="content">
	<h1>Les horaires</h1>
		<div class="flex-purshase-recap">
			
			<p:panelGrid styleClass="purshase-grid">
				<p:row styleClass="pushase-content-hours">
					<p:column styleClass="grid-center-col">Lundi</p:column>
					<p:column styleClass="grid-center-col">Fermé</p:column>
				</p:row>
				<p:row styleClass="pushase-content-hours">
					<p:column styleClass="grid-center-col">Mardi</p:column>
					<p:column styleClass="grid-center-col">08:30–13:00 | 15:30–19:30</p:column>
				</p:row>
				<p:row styleClass="pushase-content-hours">
					<p:column styleClass="grid-center-col">Mercredi</p:column>
					<p:column styleClass="grid-center-col">08:30–13:00 | 15:30–19:30</p:column>
				</p:row>
				<p:row styleClass="pushase-content-hours">
					<p:column styleClass="grid-center-col">Jeudi</p:column>
					<p:column styleClass="grid-center-col">08:30–13:00 | 15:30–19:30</p:column>
				</p:row>
				<p:row styleClass="pushase-content-hours">
					<p:column styleClass="grid-center-col">Vendredi</p:column>
					<p:column styleClass="grid-center-col">08:30–13:00 | 15:30–19:30</p:column>
				</p:row>
				<p:row styleClass="pushase-content-hours">
					<p:column styleClass="grid-center-col">Samedi</p:column>
					<p:column styleClass="grid-center-col">08:30–13:00 | 15:30–19:30</p:column>
				</p:row>
				<p:row styleClass="pushase-content-hours">
					<p:column styleClass="grid-center-col">Dimanche</p:column>
					<p:column styleClass="grid-center-col">Fermé</p:column>
				</p:row>
			</p:panelGrid>
		</div>
		<div class="index marginLR">
			<h1>nous contacter</h1>
		</div>
		<div>
		<br/>
			<p>La Maison de la Viande</p>
			<p>79, rue de la République</p>
			<p>13002 Marseille</p>
			<p>09 55 87 56 34</p>
			
			<div class="footer-element">
			<b:button href="https://www.facebook.com/lamaisondelaviandejoliette" look="link" icon-size="2x" iconAwesome="facebook-square"  />
			<b:button href="https://www.instagram.com/lamaisondelaviandejoliette/" look="link" icon-size="2x" iconAwesome="instagram"  />
			</div>
		</div>
	</ui:define>
</ui:composition>
</html>

MaisonViande-Web/src/main/webapp/purshaseRecap.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core%22%3E">

<ui:composition template="/arch.xhtml">
	<ui:define name="head">
		<f:metadata>
			<f:event listener="#{mbPurshase.ShoppingCartEmpty()}" type="preRenderView"></f:event>
		</f:metadata>
	</ui:define>
	<ui:define name="content">
		<h1>Votre commande est enregistrée !</h1>

	</ui:define>
</ui:composition>
</html>